"""empty message

Revision ID: 111fd6e785e5
Revises: 699a24d9b799
Create Date: 2025-06-23 17:31:10.573992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111fd6e785e5'
down_revision = '699a24d9b799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
