"""empty message

Revision ID: 699a24d9b799
Revises: 6072e68d5bd7
Create Date: 2025-06-23 17:29:54.536873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699a24d9b799'
down_revision = '6072e68d5bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
