"""empty message

Revision ID: 8e3ab7fe3ea6
Revises: b7f9ee0c7ca0
Create Date: 2025-06-23 16:30:48.720807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3ab7fe3ea6'
down_revision = 'b7f9ee0c7ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('activity_email_key'), type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('activity_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
