"""empty message

Revision ID: 9b0111cd8adb
Revises: 58c7420e2314
Create Date: 2025-07-18 16:47:53.313486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0111cd8adb'
down_revision = '58c7420e2314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('activity_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_date', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
