"""empty message

Revision ID: a41b5713411a
Revises: ce97e0ef7099
Create Date: 2025-06-16 16:03:16.923198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41b5713411a'
down_revision = 'ce97e0ef7099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cif', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('web', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('imagen', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('facebook', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('instagram', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('twitter', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('linkedin', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('Professional_email_key'), type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('email')
        batch_op.drop_column('lastname')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('Professional_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('linkedin')
        batch_op.drop_column('twitter')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')
        batch_op.drop_column('imagen')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('web')
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')
        batch_op.drop_column('cif')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
