"""empty message

Revision ID: cbd7898c119b
Revises: 5076794b3dac
Create Date: 2025-07-18 16:41:47.136977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd7898c119b'
down_revision = '5076794b3dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('activity_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_date', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
